name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch latest release version
        run: |
          git fetch --depth=1 origin "+refs/tags/*:refs/tags/*"
          echo "::set-env name=LATEST_VERSION::$(git tag | tail -1)"
          echo "::set-env name=SHA8::$(git rev-parse --short=8 $GITHUB_SHA)"

      - name: Build the Docker image
        run: docker build --tag "hugocms:$LATEST_VERSION.$SHA8" --tag hugocms:latest --build-arg mode=production .

      - name: Upload image to GitHub packages
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u dfkdream --password-stdin
          docker tag "hugocms:$LATEST_VERSION.$SHA8" "docker.pkg.github.com/dfkdream/hugocms/hugocms:$LATEST_VERSION.$SHA8"
          docker tag "hugocms:$LATEST_VERSION.$SHA8" "docker.pkg.github.com/dfkdream/hugocms/hugocms"
          docker push "docker.pkg.github.com/dfkdream/hugocms/hugocms"

      - name: Upload image to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u dfkdream --password-stdin
          docker rmi "docker.pkg.github.com/dfkdream/hugocms/hugocms:$LATEST_VERSION.$SHA8"
          docker rmi "docker.pkg.github.com/dfkdream/hugocms/hugocms"
          docker tag "hugocms:$LATEST_VERSION.$SHA8" "dfkdream/hugocms:$LATEST_VERSION.$SHA8"
          docker tag "hugocms:$LATEST_VERSION.$SHA8" "dfkdream/hugocms"
          docker push "dfkdream/hugocms"
